Allow CR with custom dashboard image that is different from general custom image or default image
Opster/opensearch-k8s-operator pull request #177
Opened 2022-06-05 07:41 UTC by aarontams

**Task** Allow config the OpenSearchCluster CR to use a specific image for the dashboards only

**Limit** Currently, the OpenSearchCluster CR _**only**_ allows customize the dashboard image through the `spec.general.image`. But the CR value in `spec.general.image` will also be used by all the opensearch cluster nodes (master, ingest, and data).

**Solution** To allow the CR to customize the dashboard image only without affecting other components, the simplest way is to introduce an `ImageSpec` struct in `spec.dashboards`. For example:
```
spec:
  dashboards:
    imagePullPolicy: Always
    image: my.io/awesomeapps/opensearch-dashboards:3.2.1-canary
```

**Implementation** With this MR, the opensearch operator will choose the dashboard image in the following order:
1. CR value in`spec.dashboards.image` if specified.
2. CR value in `spec.general.image` if specified.
3. Default hard coded `docker.io/opensearchproject/opensearch-dashboards:` + cr.Spec.Dashboards.Version

2022-06-05 07:48 UTC, aarontams commented on charts/opensearch-operator/templates/opensearchclusters.opensearch.opster.io-crd.yaml
> +                    type: array
When I did the docket-build, as expect the opensearch-operator/config/crd/bases/opensearch.opster.io_opensearchclusters.yaml file was updated.

My question is even before my PR, the updated opensearch.opster.io_opensearchclusters.yaml content is different from charts/opensearch-operator/templates/opensearchclusters.opensearch.opster.io-crd.yaml 

**I am not sure this snippet is needed for PR or not. I can remove it if it is not needed.**

2022-06-05 07:48 UTC, aarontams commented on opensearch-operator/pkg/helpers/reconcile-helpers.go
> -
Since this code snippet is used 3 times in this go file, refactoring the code to call `useCustomImage` func for easy maintenance going forward.

2022-06-05 15:41 UTC, aarontams commented
**Reviewers**
I am not seeing the `spec.general.image` (imagePullPolicy, imagePullSecrets) defined in  [crd.md](https://github.com/Opster/opensearch-k8s-operator/blob/main/docs/designs/crd.md). I am hesitate to add the new fields from this MR to `spec.database`. Please advise.

2022-06-08 15:27 UTC, swoehrl-mw requested changes
Hi @aarontams. Thank you for your PR.
Could you please add a unittest for the new functionality (probably in `opensearch-operator/pkg/reconcilers/dashboards_test.go`)
and please add the new fields to the crd.md (that the fields for `spec.general.image` are not there is an omission, in general every field of the CRD should be documented).
Otherwise code looks good to me.

2022-06-09 04:01 UTC, aarontams commented
> Could you please add a unittest for the new functionality (probably in opensearch-operator/pkg/reconcilers/dashboards_test.go)

Will do in next PR update.

> and please add the new fields to the crd.md (that the fields for `spec.general.image` are not there is an omission, in general every field of the CRD should be documented).

I was thinking about adding the new fields to crd.md, but didn't see the ImageSpec defined in [GeneralConfig](https://github.com/Opster/opensearch-k8s-operator/blob/main/docs/designs/crd.md#--generalconfig).

Yes, I will add that in next PR update.

2022-06-09 07:10 UTC, aarontams commented
@swoehrl-mw 
Updated the PR with 
- new fields in crd.md
- unittest for the new functionality

Looking forward to having you to review it again.

2022-06-09 12:28 UTC, swoehrl-mw approved these changes
LGTM

2022-06-09 12:29 UTC, merged