Adding node selectors, affinity and tolerations to the dashboard pods
Opster/opensearch-k8s-operator pull request #242
Opened 2022-08-10 08:03 UTC by madhukarmmallia-plivo

2022-08-10 11:49 UTC, swoehrl-mw reviewed
Hi @madhukarmmallia-plivo. Thank you for your PR. 
Can you add a little unittest to check the new fields are correctly added to the dashboard deployment (more as a regression test)? Probably best in `controllers/dashboard_test.go`. Other than that it looks good.

2022-08-12 08:51 UTC, madhukarmmallia-plivo commented
Hello @swoehrl-mw! Could you please take a look now?

2022-08-12 11:36 UTC, swoehrl-mw requested changes
There are some problems with the comparisons in your test, see my code comments. You can always run the tests locally with `make test` to make sure they work before pushing.

Regarding the failing lint job: Not sure why but looks like a out-of-memory kill. You can locally verify there are no lint problems by running `make lint`.

2022-08-12 11:36 UTC, swoehrl-mw commented on opensearch-operator/controllers/dashboard_test.go
> +				Expect(deployment.Spec.Template.Spec.NodeSelector).To(ContainElement(map[string]string{
```suggestion
				Expect(deployment.Spec.Template.Spec.NodeSelector).Should(Equal(map[string]string{
```
The `ContainElement` does not work as intended for maps.

2022-08-12 11:36 UTC, swoehrl-mw commented on opensearch-operator/controllers/dashboard_test.go
> +				Expect(deployment.Spec.Template.Spec.Affinity).To(ContainElement(corev1.Affinity{}))
This is not a list, so you need to use `Expect(...).To(Equal(...))`. And you are comparing pointer to value, so you need to dereference the pointer first.

2022-08-12 11:36 UTC, swoehrl-mw commented on opensearch-operator/controllers/dashboard_test.go
> +				Expect(deployment.Spec.Replicas).To(Equal(2))
You are comparing a pointer with a value, and the configured replicas is `3`. You can use the `k8s.io/utils/pointer` package and create a pointer:
```suggestion
				Expect(deployment.Spec.Replicas).To(Equal(pointer.Int32(3)))
```

2022-08-16 08:27 UTC, madhukarmmallia-plivo commented
@swoehrl-mw I have updated tests as per your feedback. Could you please review it?

2022-08-18 15:42 UTC, madhukarmmallia-plivo commented
Hi @idanl21 Could you also please have a look at this?

2022-08-19 13:50 UTC, swoehrl-mw approved these changes
LGTM

2022-08-19 13:51 UTC, merged