Add docs on custom admin
Opster/opensearch-k8s-operator pull request #346
Opened 2022-11-03 16:02 UTC by idanl21

After a lot of issues opened, I decided to test it on my own and write some guide about it.
We also need still to figure out why users fail to change the admin password on running clusters.

2022-11-04 13:36 UTC, CodeGlitcher commented
Hi there,

I think this is a bad solution to changing the admin password.
(The reason why noone changes it, is because its to hard)
Because now i have to put my password in some online tool and add the hash to my code or use a local tool to create the hash..

Would it not be better for the operator to use the admin cert that is generated to communicate with the cluster.
And let the operator create a random admin user (or let users now define a admin user with OpensearchUser object)

I was going to make a issue but then i saw this pr. 
So I thought I would post my thoughts here because we are running into the same problem.
We want a good way to change the admin password, but it is all a bit hacky.

a follow up issue we have is that each time there is a change in the security config files.
The operator restarts opensearch-cluster-securityconfig-update. But this removes alle the users created by the operator.
Because the security tooling removes all users that are not in the internalusers.yml. 
After the job the operator does not seem to try to recreate the OpenSearchUsers unil a restart

(When we deployed opensearch ourself with pure docker 
we detected if the security index was already present and used
/securityadmin.sh -f $1 to apply indivudiual files. 
and we skipped internaluser.yml to preserve our users)

2022-11-06 16:46 UTC, idanl21 commented
> Hi there,
> 
> I think this is a bad solution to changing the admin password. (The reason why noone changes it, is because its to hard) Because now i have to put my password in some online tool and add the hash to my code or use a local tool to create the hash..
> 
> Would it not be better for the operator to use the admin cert that is generated to communicate with the cluster. And let the operator create a random admin user (or let users now define a admin user with OpensearchUser object)
> 
> I was going to make a issue but then i saw this pr. So I thought I would post my thoughts here because we are running into the same problem. We want a good way to change the admin password, but current setup is a bit hacky.
> 
> We also tryed to create the admin user in a seperate job, but this also causes some startup problems, because when the operator cant create a user it simple stops creating it, rather then creating it when we have created the admin user.
> 
> a follow up issue we have is that each time there is a change in the security config files. The operator restarts opensearch-cluster-securityconfig-update. But this removes alle the users created by the operator. Because the security tooling removes all users that are not in the internalusers.yml. After the job the operator does not seem to try to recreate the OpenSearchUsers unil a restart
> 
> (When we deployed opensearch ourself with pure docker we detected if the security index was already present and used /securityadmin.sh -f $1 to apply indivudiual files. and we skipped internaluser.yml to preserve our users)

So a lot of customers asked as for that feature, people want to know the admin users and to be able to configure it?
@swoehrl-mw @prudhvigodithi, what is your opinion ?

2022-11-07 14:46 UTC, swoehrl-mw commented
@CodeGlitcher You make several points:

> Would it not be better for the operator to use the admin cert that is generated to communicate with the cluster.

That would be a way but also makes it more complex so we'll have to think about this more deeply.

> And let the operator create a random admin user (or let users now define a admin user with OpensearchUser object)

At the moment the operator follows how opensearch itself does it and that means default credentials and the user has to change them, which is possible (if a little cumbersone) the way @idanl21 wants to document it in this PR.

> We also tryed to create the admin user in a seperate job [...]

In terms of configuration and securityconfig the operator is all-in, you are not supposed to manage parts separately as that would make everything more complex.

> a follow up issue we have is that each time there is a change in the security config files [...]

This is a known and open issue: #254 and we will have to think on how we handle that.

2022-11-08 14:25 UTC, swoehrl-mw requested changes

2022-11-08 14:25 UTC, swoehrl-mw commented on docs/userguide/main.md
> +In order to create your cluster with other than default `admin:admin` user you will have to add walk through those steps:
```suggestion
In order to create your cluster with an adminuser different from the default `admin:admin` you will have to walk through the following steps: 
```

2022-11-08 14:25 UTC, swoehrl-mw commented on docs/userguide/main.md
> +Second you will have to create your own `securityconfig-secret` secret (take a look about the at opensearch-operator/examples/securityconfig-secret.yaml for an example).
```suggestion
Second you will have to create your own `securityconfig-secret` secret (take a look at `opensearch-operator/examples/securityconfig-secret.yaml` for an example).
```

2022-11-08 14:25 UTC, swoehrl-mw commented on opensearch-operator/examples/opensearch-cluster-custom-admin-user.yaml
> +apiVersion: opensearch.opster.io/v1
Please add a comment as first line explaining what this file is an example for and when to use it

2022-11-10 11:25 UTC, merged