Support types On Dashboards Service
Opster/opensearch-k8s-operator pull request #389
Opened 2022-12-11 21:14 UTC by simonmacklin

This PR allows the user to use the available service types to expose opensearch dashboards.  This PR replaces 

```Extend CRD to configure dashboards k8s service #348```

It is the same author but I used the wrong organisation and need to switch to my personal one so I will close the PR above.

2022-12-19 15:39 UTC, simonmacklin commented
Hey @swoehrl-mw 

Do you require any further changes for this PR?

2022-12-21 15:01 UTC, swoehrl-mw requested changes
Hi @simonmacklin.
The following small things are missing for me:
* Please add a short paragraph to the userguide.
* Please also copy the changed CRD yaml into the helm chart (see https://github.com/Opster/opensearch-k8s-operator/blob/main/docs/developing.md#submitting-a-pr)

2022-12-25 18:04 UTC, idanl21 reviewed
Hey @simonmacklin, first of all thank you for contributing !
second, looks good but we do must add some explanation to the userguide before merging now methods.
Also, like @swoehrl-mw said, we need to add the new CRD Yaml to the helm chart dir to keep it ailing with the repo :) 
please add it and i will merge the PR.

2023-01-09 11:38 UTC, swoehrl-mw requested changes

2023-01-09 11:38 UTC, swoehrl-mw commented on docs/userguide/main.md
> +## Configuring opensearch_dashboards.yml
Looks like there was a hickup with the merging in of the newest main and some paragraphs are now duplicated. Can you please fix that?

2023-01-09 12:52 UTC, idanl21 approved these changes

2023-01-09 12:53 UTC, merged

2023-01-09 13:04 UTC, swoehrl-mw commented
@simonmacklin Fixed the userguide myself so we could add your PR to the new release.