added flag to skip adding initContainers to the OpenSearch StatefulSet
Opster/opensearch-k8s-operator pull request #423
Opened 2023-02-02 10:30 UTC by djcass44

Signed-off-by: Django Cass <django@dcas.dev>

This Operator is unable to be used on OpenShift or clusters that block pods from running as `root` as the `initContainer` used to `chown` the data volume is hardcoded to run as `root` and cannot be disabled.

This MR adds a flag to the OpenSearch CustomResourceDefinition which allows users to skip the addition of the `chown` `initContainer`. The flag is named `skip` rather than `enabled` to retain backwards compatibility with previous versions of the Operator.

I personally don't consider removing the `initContainer` a loss of functionality as the `chown` behaviour is provided by modern CSI-based Kubernetes clusters via the [`fsGroup` security context functionality](https://kubernetes.io/docs/tasks/configure-pod-container/security-context/#configure-volume-permission-and-ownership-change-policy-for-pods).

2023-02-03 12:51 UTC, swoehrl-mw commented
Hi @djcass44. 
I can see and agree that making the chown initcontainer optional is worthwile. But is the CRD the best place to configure this? Looking at it this is behaviour that is the same for all opensearch clusters in the same kubernetes cluster (the kubernetes cluster either is openshift or has the csi capability or not). So IMO this is something that should be better configured in the helm chart values and not in the CRD.

2023-02-03 22:38 UTC, djcass44 commented
@swoehrl-mw that's a good point. I've updated the MR to use an environment variable and modified the chart to allow the user to set it.

2023-02-09 09:54 UTC, swoehrl-mw requested changes
Left some comments. Please also resolve the merge conflicts.

2023-02-09 09:54 UTC, swoehrl-mw commented on charts/opensearch-operator/Chart.yaml
> +version: 2.2.1
No need to update the version, our release process will do that automatically.

2023-02-09 09:54 UTC, swoehrl-mw commented on opensearch-operator/pkg/builders/cluster.go
> +	if os.Getenv(helpers.SkipInitContainerEnvVariable) != "true" {
There is `strconv.ParseBool` to parse a string to a bool. That allows the users to use different variants of `true`.
Also please move the env lookup part into `helpers/constants.go` (like already done with `ParallelRecoveryMode` and `ClusterDnsBase`).

2023-02-09 09:54 UTC, swoehrl-mw commented on opensearch-operator/pkg/builders/cluster_test.go
> +		It("should skip the init containers", func() {
Please extend the description a bit to make clear what is tested. Ala "should skip the init container as SKIP_INIT_CONTAINER is set".

2023-02-09 09:54 UTC, swoehrl-mw commented on opensearch-operator/pkg/builders/cluster_test.go
> +		})
Please also test the `NewBootstrapPod` function in the same way.

2023-02-09 09:54 UTC, swoehrl-mw commented on charts/opensearch-operator/CHANGELOG.md
> +- Added support for setting arbitrary environment variables on the operator-manager
No need to add this, we now only use the changelog in the gitub release.

2023-02-09 11:13 UTC, djcass44 commented
@swoehrl-mw thanks for the comments. I believe I have addressed them all.

2023-02-13 12:50 UTC, swoehrl-mw approved these changes
LGTM

2023-02-13 13:00 UTC, merged