Allow setting pod security context through CRD
Opster/opensearch-k8s-operator pull request #456
Opened 2023-03-06 10:57 UTC by saketmht

This implements #373 

Changes:

1. Added `PodSecurityContext` and `SecurityContext` fields for cluster and dashboard pods.
2. Added unit test for the same.
3. Doc updates for the added fields.

2023-03-06 11:32 UTC, saketmht commented
@swoehrl-mw Can you help me with why the lint job failed? I don't see any error messaged in the run and local lint check didn't report any errors either. And could you review the PR as well?

2023-03-06 18:10 UTC, swoehrl-mw commented
@saketmht Looks like the linter job ran into out-of-memory. Not much we can do except try to fiddle with the configuration. But if it passes locally then that's good enough for me.
Regarding a review: It'll likely be a few days until I can get to it, if @idanl21 pitches in it might be faster.

2023-03-12 13:35 UTC, idanl21 approved these changes
Hey, just lets add parmetrs on builders, also cloned it, and LINT passed so it sok for my side

2023-03-12 13:35 UTC, idanl21 commented on opensearch-operator/pkg/builders/cluster.go
> +							SecurityContext: cr.Spec.General.SecurityContext,
Lets add parameter for that , to keep on the convention .

2023-03-12 13:35 UTC, idanl21 commented on opensearch-operator/pkg/builders/dashboards.go
> +							SecurityContext: cr.Spec.Dashboards.SecurityContext,
also here

2023-03-12 14:50 UTC, saketmht commented
@swoehrl-mw @idanl21 Updated PR according to comments.

2023-03-16 15:17 UTC, swoehrl-mw requested changes
@saketmht Can you add a little section to the userguide about this feature, maybe also explain in one sentence why someone should need this? That should make it easier to find for users.
Code LGTM.

2023-03-16 17:48 UTC, saketmht commented
@swoehrl-mw Added a section for security context in the userguide.

2023-03-17 14:46 UTC, swoehrl-mw approved these changes

2023-03-17 14:46 UTC, merged