added securityContext to manager's pod
Opster/opensearch-k8s-operator pull request #461
Opened 2023-03-12 13:30 UTC by idanl21

added - https://github.com/Opster/opensearch-k8s-operator/issues/457

2023-03-12 14:10 UTC, saketmht commented on charts/opensearch-operator/templates/opensearch-operator-controller-manager-deployment.yaml
> +        securityContext:
The securityContext field already exists below. I don't think we need to create another one. Just add the value that already exists in the values.yaml

2023-03-12 14:13 UTC, saketmht commented
We need a field `podSecurityContext` for the entire deployment's securityContext as well
https://github.com/Opster/opensearch-k8s-operator/blob/4edd47a61f05e2a3b2e38d826f9fb5ca33e55f1f/charts/opensearch-operator/templates/opensearch-operator-controller-manager-deployment.yaml#L66
and securityContext for the `kubeRbacProxy` container would also be nice.

2023-03-16 15:14 UTC, swoehrl-mw requested changes
I agree with @saketmht's review.

2023-03-27 05:42 UTC, saketmht requested changes
The changes now are only for the `manager` container. Like I mentioned in my earlier comment, I think we should support setting security context for the entire deployment as well as the `kuberbacproxy` container.

2023-03-27 05:42 UTC, saketmht commented on charts/opensearch-operator/values.yaml
> +  allowPrivilegeEscalation: false
This should be under `securityContext`

2023-03-30 14:03 UTC, swoehrl-mw requested changes

2023-03-30 14:03 UTC, swoehrl-mw commented on charts/opensearch-operator/values.yaml
> +    securityContext:
Wrong indentation.

2023-04-10 04:34 UTC, saketmht commented on charts/opensearch-operator/values.yaml
> +  # Set this to false to disable the experimental parallel recovery in case you are experiencing problems
This comment should be above parallelRecoveryEnabled flag at Line37

2023-04-12 16:15 UTC, saketmht commented
Should the file diff be this large? Did the merge/rebase go wrong? The indentation error as swoehrl-mw mentioned also needs to be fixed.

2023-05-01 15:27 UTC, saketmht commented
@idanl21 Any updates on this PR? Would really like this feature to be checked in as we require setting security context for the pods in our environment.

2023-05-23 11:16 UTC, saketmht commented
> Hey friends, @saketmht @swoehrl-mw What about that PR?

@idanl21 there is still a mistake in the values.yaml Line 89. The indentation is incorrect for securityContext. And I am still not sure why the file diff is so large compared to main branch.

2023-06-15 17:11 UTC, saketmht commented
@idanl21 Are you still working on this? We would really like this feature to be included in the next release. If you don't have bandwidth, do you want me to raise a PR for this?

2023-06-26 14:55 UTC, idanl21 commented
Hey @saketmht 
Sorry on the delay, but that feature is allready finished, waiting only for review :) 
You are more then welcome to take a look and we will release it in next version

2023-06-27 07:44 UTC, swoehrl-mw commented
Hi @idanl21. There is something weird with your PR, you have diffs for things that are already in main (for example `securityContext` for `GeneralConfig` and `DashboardsConfig`). Please check your PR and either fix it or recreate it. As it is now it cannot be reviewed or merged.

2023-07-14 11:44 UTC, swoehrl-mw commented
Superseded by PR #561.

2023-07-14 11:44 UTC, closed without merging