Add CRD for actiongroups
Opster/opensearch-k8s-operator pull request #489
Opened 2023-04-17 04:46 UTC by saketmht

This implements #485 

Changes:

- Add new CRD to managed actiongroups in opensearch
- Added code for the controller to watch and reconcile the CRD
- Added tests for the controller code
- Some refactoring of existing code
- Doc changes

2023-04-17 04:49 UTC, saketmht commented
@swoehrl-mw @idanl21 Could you please review? 

PS - The change in the OS Cluster CRD is due to the recent PR #476 which added new fields to the CRD but didn't update the CRD using `make manifests`.

2023-05-01 15:26 UTC, saketmht commented
@swoehrl-mw Could you please review?

2023-05-05 11:41 UTC, swoehrl-mw requested changes
Code looks good to me. One minor thing. Once that is changed we can merge.

2023-05-05 11:55 UTC, saketmht commented on docs/developing.md
> +        cp opensearch-operator/config/crd/bases/opensearch.opster.io_opensearchactiongroups.yaml charts/opensearch-operator/templates/OpensearchActionGroup-crd.yaml
updated the release workflow file

2023-05-05 12:13 UTC, swoehrl-mw approved these changes

2023-05-05 12:13 UTC, merged