Delete OSD deployment for emptyDir recovery
Opster/opensearch-k8s-operator pull request #608
Opened 2023-09-14 06:25 UTC by saketmht

When deleting the sts and setting cluster initialized to false for emptyDir failure scenarios. the osd pod simply tried to reconnect to the cluster. After the cluster is back up, osd is successfully able to connect but it doesn't recreate the .kibana index as it is only created when the pod is started. 

Changes:

- Delete OSD deploy so that pods will restart and .kibana index will be recreated successfully on cluster initialization.

2023-09-25 14:15 UTC, swoehrl-mw requested changes

2023-09-25 14:15 UTC, swoehrl-mw commented on opensearch-operator/pkg/helpers/helpers.go
> +func DeleteOSDDeployment(ctx context.Context, k8sClient client.Client, clusterName, clusterNamespace string) error {
Please rename to `DeleteDashboardsDeployment`, the OS/OSD abbreviation is normally not used in the code.

2023-09-25 14:15 UTC, swoehrl-mw commented on opensearch-operator/pkg/reconcilers/cluster.go
> +		}
I prefer this to run before `Initialized` it reset to false

2023-09-26 12:02 UTC, saketmht commented
@swoehrl-mw Updated based on review

2023-09-27 14:02 UTC, swoehrl-mw approved these changes

2023-09-27 14:02 UTC, merged