First version CRD DOCS
Opster/opensearch-k8s-operator pull request #91
Opened 2022-03-31 12:20 UTC by idanl21

- First version of CRD DOCS
- change busybox image to opster-pub-ecr image (from rate limit errors on past image)

2022-04-04 00:44 UTC, dbason commented on opensearch-operator/pkg/builders/cluster.go
> +	return "opensearchproject/opensearch:1.0.0"
I think this is dead code that could be removed.

2022-04-04 00:44 UTC, dbason commented on docs/designs/crd.md
> +<table>
Any reason to use a html table over a markdown one?

2022-04-20 06:34 UTC, swoehrl-mw requested changes
This is missing some fields:
* nodePool.persistence
* nodePool.additionalConfig
* confMgmt
* general.drainDataNodes
* general.defaultRepo
* Fields from ImageSpec in general
* DashboardsTlsConfig
* Security and its subobjects are completely missing
* probably some more I didn't see

Types `object` should be the respective type, e.g. `[]NodePool` instead of `[]object`.

All field names should be written exactly as they appear in the YAML (e.g. `jvm` instead of `JVM`, `tolerations` instead of `Tolerations`).

2022-04-20 06:34 UTC, swoehrl-mw commented on docs/designs/crd.md
> +        <td>The nodePools object is build from nodePool objects and define different nodePools  in OpensearchCluster. Thats the main resource that responsible for deploying OpensearchCluster Stateful
```suggestion
        <td>List of objects that define the different nodePools in an OpensearchCluster. Each nodePool represents a group of nodes with the same opensearch roles and resources. Each nodePool is deployed as a Kubernetes StatefulSet. Together they form the opensearch cluster.</td>
```

2022-04-20 06:34 UTC, swoehrl-mw commented on docs/designs/crd.md
> +        <td>Responsible about enabling additional OpensaerchOperator components (reconcilers)  </td>
```suggestion
        <td>Config object to enable additional OpensearchOperator features/components</td>
```

2022-04-20 06:34 UTC, swoehrl-mw commented on docs/designs/crd.md
> +        <td>Vendor declaration (sts docker image is built for it)</td>
```suggestion
        <td>Vendor distribution to use for the cluster, currently only opensearch is supported</td>
```

2022-04-20 06:34 UTC, swoehrl-mw commented on docs/designs/crd.md
> +        <td> Opensearch applicative version  </td>
```suggestion
        <td>Version of opensearch to deploy</td>
```

2022-04-20 06:34 UTC, swoehrl-mw commented on docs/designs/crd.md
> +        <td>k8s service name</td>
```suggestion
        <td>Name to use for the k8s service to expose the cluster internally</td>
```

2022-04-20 06:34 UTC, swoehrl-mw commented on docs/designs/crd.md
> +        <td>string</td>
```suggestion
        <td>map[string]string</td>
```

2022-04-20 06:34 UTC, swoehrl-mw commented on docs/designs/crd.md
> +        <td>false</td>
```suggestion
        <td></td>
```

2022-04-20 06:34 UTC, swoehrl-mw commented on docs/designs/crd.md
> +        <td>defining Dashbaord TLS configuration</td>
```suggestion
        <td>TLS-related configuration for Dashboards</td>
```

2022-04-20 06:34 UTC, swoehrl-mw commented on docs/designs/crd.md
> +Every NodePool is defining different Opensearch Nodes StatefulSet
```suggestion
Each NodePool represents a group of nodes in the OpenSearch cluster that have the same role and resources. They are deployed as Kubernetes StatefulSets
```

2022-04-20 06:34 UTC, swoehrl-mw commented on docs/designs/crd.md
> +        <td>defines NodePool deployment's replicas</td>
```suggestion
        <td>Number of nodes/replicas in the pool</td>
```

2022-04-20 06:34 UTC, swoehrl-mw commented on docs/designs/crd.md
> +        <td> - </td>
```suggestion
        <td>30Gi</td>
```

2022-04-20 06:34 UTC, swoehrl-mw commented on docs/designs/crd.md
> +        <td>true</td>
```suggestion
        <td>false</td>
```
Is not required

2022-04-20 06:34 UTC, swoehrl-mw commented on docs/designs/crd.md
> +      </tr><tr>
NodePool has no TLS config, the entire table row is wrong here

2022-04-20 06:34 UTC, swoehrl-mw commented on docs/designs/crd.md
> +        <td>Default Opensearch resources</td>
```suggestion
        <td></td>
```
If not set uses empty resources (meaning no requests/limits on the pods)

2022-04-20 06:34 UTC, swoehrl-mw commented on docs/designs/crd.md
> +        <td> define Opensearch roles to the nodeGroup </td>
```suggestion
        <td>List of OpenSearch roles to assign to the nodePool</td>
```

2022-04-20 06:34 UTC, swoehrl-mw commented on docs/designs/crd.md
> +        <td> declare JVM</td>
```suggestion
        <td>JVM args. Use this to define heap size (recommendation: Set to half of memory request)</td>
```

2022-04-20 06:34 UTC, swoehrl-mw commented on docs/designs/crd.md
> +        <td> half of the STS requests  </td>
```suggestion
        <td>-Xmx512M -Xms512M</td>
```

2022-04-20 06:34 UTC, swoehrl-mw commented on docs/designs/crd.md
> +        <td><b>ExtraConfig</b></td>
```suggestion
        <td><b>additionalConfig</b></td>
```

2022-04-28 08:14 UTC, merged